package fon.master.onlineshop.gui.product.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;

import fon.master.onlineshop.domain.Product;

public class ProductGridCell extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label productNameLbl;
	@AutoGenerated
	private Button addToCartBtn;
	@AutoGenerated
	private Embedded productImg;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ProductGridCell(Product product) {
		buildMainLayout(product);
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout(Product product) {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setStyleName("cellLayout");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("200px");
		mainLayout.setHeight("260px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("200px");
		setHeight("260px");
		
		// productImg
		productImg = new Embedded();
		productImg.setStyleName("productImg");
		productImg.setImmediate(false);
		productImg.setWidth("200px");
		productImg.setHeight("260px");
		productImg.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		productImg.setType(1);
		productImg.setMimeType("image/png");
		mainLayout.addComponent(productImg, "top:0.0px;left:0.0px;");
		
		// addToCartBtn
		addToCartBtn = new Button();
		addToCartBtn.setStyleName("addToCartBtn");
		addToCartBtn.setCaption("Add to Cart");
		addToCartBtn.setImmediate(false);
		addToCartBtn.setWidth("-1px");
		addToCartBtn.setHeight("-1px");
		mainLayout.addComponent(addToCartBtn, "top:220.0px;left:60.0px;");
		
		// productNameLbl
		productNameLbl = new Label();
		productNameLbl.setStyleName("productNameLbl");
		productNameLbl.setImmediate(false);
		productNameLbl.setWidth("160px");
		productNameLbl.setHeight("-1px");
		productNameLbl.setValue(product.getName());
		mainLayout.addComponent(productNameLbl, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

}
